
type User {
    name: String!
    email: String! @unique
    tabs: [Tab!] @relation(name: "user_tabs")
    chords: [ChordChart!] @relation(name: "user_chordcharts")
}

type Track {
    spotifyId: String! @unique
    tabs: [Tab!]! @relation
    chords: [ChordChart!]! @relation
}


type Tab {
    approved: Boolean!
    musicXml: String!
    rating: Int!
    author: User! @relation(name: "user_tabs")
    description: String!
    dateSubmitted: String!
    track: Track! @relation
}


type ChordChart {
    approved: Boolean!
    chords: [Beat!]!
    rating: Int!
    author: User! @relation(name: "user_chordcharts")
    description: String!
    dateSubmitted: String!
    track: Track @relation
}

type Beat @embedded {
    start: Float!
    duration: Float!
    chord: Chord!
}

type Chord @embedded {
    tonality: String!
    type: String!
    extension: String
}

